[package]
name = "rustfsm_trait"
version = "0.1.0"
authors = ["Spencer Judge <spencer@temporal.io>"]
edition = "2021"
license-file = "LICENSE.txt"
description = "Trait sub-crate of the `rustfsm` crate"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[package.metadata.workspaces]
independent = true
