[package]
name = "temporal-sdk-core-test-utils"
version = "0.1.0"
authors = ["Spencer Judge <spencer@temporal.io>"]
edition = "2021"
license-file = { workspace = true }

[[bin]]
name = "histfetch"
path = "src/histfetch.rs"

[features]
default = ["ephemeral-server"]
ephemeral-server = ["temporal-sdk-core/ephemeral-server"]

[dependencies]
anyhow = "1.0"
assert_matches = "1"
async-trait = "0.1"
base64 = "0.22"
bytes = "1.3"
futures-util = { version = "0.3", default-features = false }
log = "0.4"
parking_lot = "0.12"
prost = { workspace = true }
prost-types = { workspace = true }
rand = "0.8"
rmp-serde = "1.1"
serde_json = "1.0"
temporal-client = { path = "../client" }
temporal-sdk = { path = "../sdk" }
temporal-sdk-core = { path = "../core" }
temporal-sdk-core-api = { path = "../core-api" }
thiserror = { workspace = true }
tokio = "1.1"
tokio-util = { version = "0.7" }
tracing = "0.1"
url = "2.2"
uuid = "1.1"

[dependencies.temporal-sdk-core-protos]
path = "../sdk-core-protos"
version = "0.1"

[lints]
workspace = true
