scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'otel-collector:8889' ]
      - targets: [ 'otel-collector:8888' ]
  - job_name: 'direct-prom'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'localhost:9999' ]
