name: Push to Buf Registry

on:
  push:
    tags:
      - 'v**'
    branches:
      - master
permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          version: 1.49.0
          token: ${{ secrets.BUF_TEMPORALIO_TOKEN }}
