name: ci
on:
  pull_request:
permissions:
  contents: read
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21'
      - uses: arduino/setup-protoc@v2
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2
      - run: make ci-build
      - name: Fail if the repo is dirty
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Detected uncommitted changes."
            git status
            git diff
            exit 1
          fi
