version: "3.5"

services:
  build:
    build:
      context: ..
      dockerfile: ./.buildkite/Dockerfile
    environment:
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
    volumes:
      - ../:/temporal
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
