//! Runtime entry traits implemented by workflow definitions and message handlers.

use crate::{
    SyncWorkflowContext, WorkflowContext, WorkflowContextView,
    runtime::{model::WorkflowTermination, types::WorkflowDefinitionDescriptor},
};
use futures_util::future::{FutureExt, LocalBoxFuture};
use temporalio_common_wasm::{
    QueryDefinition, SignalDefinition, UpdateDefinition, WorkflowDefinition,
    data_converters::{
        GenericPayloadConverter, PayloadConversionError, PayloadConverter, SerializationContext,
        SerializationContextData, TemporalDeserializable, TemporalSerializable,
    },
    protos::temporal::api::{
        common::v1::{Payload, Payloads},
        failure::v1::Failure,
    },
};

/// Error type for workflow operations
#[derive(Debug, thiserror::Error)]
pub enum WorkflowError {
    /// Error during payload conversion
    #[error("Payload conversion error: {0}")]
    PayloadConversion(#[from] PayloadConversionError),

    /// Workflow execution error
    #[error("Workflow execution error: {0}")]
    Execution(#[from] anyhow::Error),
}

impl From<WorkflowError> for Failure {
    fn from(err: WorkflowError) -> Self {
        Failure {
            message: err.to_string(),
            ..Default::default()
        }
    }
}

/// Trait implemented by workflow structs to enable execution by the worker.
///
/// This trait is typically generated by the `#[workflow_methods]` macro and should not
/// be implemented manually in most cases.
pub trait WorkflowImplementation: Sized + 'static {
    /// The marker struct for the run method that implements `WorkflowDefinition`
    type Run: WorkflowDefinition;

    /// Whether this workflow has a user-defined `#[init]` method.
    /// Set to `true` by the macro when `#[init]` is present, `false` otherwise.
    const HAS_INIT: bool;

    /// Whether the init method accepts the workflow input.
    /// If true, input goes to init. If false, input goes to run.
    const INIT_TAKES_INPUT: bool;

    /// Returns the workflow type name.
    fn name() -> &'static str;

    /// Returns the exported workflow definition metadata for this workflow.
    fn definition() -> WorkflowDefinitionDescriptor;

    /// Initialize the workflow instance.
    fn init(
        ctx: WorkflowContextView,
        input: Option<<Self::Run as WorkflowDefinition>::Input>,
    ) -> Self;

    /// Execute the workflow's main run function.
    fn run(
        ctx: WorkflowContext<Self>,
        input: Option<<Self::Run as WorkflowDefinition>::Input>,
    ) -> LocalBoxFuture<'static, Result<Payload, WorkflowTermination>>;

    /// Dispatch an update request by name. Returns `None` if no handler for that name.
    fn dispatch_update(
        _ctx: WorkflowContext<Self>,
        _name: &str,
        _payloads: Payloads,
        _converter: &PayloadConverter,
    ) -> Option<LocalBoxFuture<'static, Result<Payload, WorkflowError>>> {
        None
    }

    /// Validate an update request by name.
    fn validate_update(
        &self,
        _ctx: WorkflowContextView,
        _name: &str,
        _payloads: &Payloads,
        _converter: &PayloadConverter,
    ) -> Option<Result<(), WorkflowError>> {
        None
    }

    /// Dispatch a signal by name.
    fn dispatch_signal(
        _ctx: WorkflowContext<Self>,
        _name: &str,
        _payloads: Payloads,
        _converter: &PayloadConverter,
    ) -> Option<LocalBoxFuture<'static, Result<(), WorkflowError>>> {
        None
    }

    /// Dispatch a query by name.
    fn dispatch_query(
        &self,
        _ctx: WorkflowContextView,
        _name: &str,
        _payloads: &Payloads,
        _converter: &PayloadConverter,
    ) -> Option<Result<Payload, WorkflowError>> {
        None
    }
}

/// Trait for executing synchronous signal handlers on a workflow.
pub trait ExecutableSyncSignal<S: SignalDefinition>: WorkflowImplementation {
    /// Handle an incoming signal with the given input.
    fn handle(&mut self, ctx: &mut SyncWorkflowContext<Self>, input: S::Input);

    /// Dispatch the signal with payload deserialization.
    fn dispatch(
        ctx: WorkflowContext<Self>,
        payloads: Payloads,
        converter: &PayloadConverter,
    ) -> LocalBoxFuture<'static, Result<(), WorkflowError>> {
        match deserialize_input::<S::Input>(payloads.payloads, converter) {
            Ok(input) => {
                let mut sync_ctx = ctx.sync_context();
                ctx.state_mut(|wf| Self::handle(wf, &mut sync_ctx, input));
                std::future::ready(Ok(())).boxed_local()
            }
            Err(e) => std::future::ready(Err(e)).boxed_local(),
        }
    }
}

/// Trait for executing asynchronous signal handlers on a workflow.
pub trait ExecutableAsyncSignal<S: SignalDefinition>: WorkflowImplementation {
    /// Handle an incoming signal with the given input.
    fn handle(ctx: WorkflowContext<Self>, input: S::Input) -> LocalBoxFuture<'static, ()>;

    /// Dispatch the signal with payload deserialization.
    fn dispatch(
        ctx: WorkflowContext<Self>,
        payloads: Payloads,
        converter: &PayloadConverter,
    ) -> LocalBoxFuture<'static, Result<(), WorkflowError>> {
        match deserialize_input::<S::Input>(payloads.payloads, converter) {
            Ok(input) => Self::handle(ctx, input).map(|()| Ok(())).boxed_local(),
            Err(e) => std::future::ready(Err(e)).boxed_local(),
        }
    }
}

/// Trait for executing query handlers on a workflow.
pub trait ExecutableQuery<Q: QueryDefinition>: WorkflowImplementation {
    /// Handle a query with the given input and return the result.
    fn handle(
        &self,
        ctx: &WorkflowContextView,
        input: Q::Input,
    ) -> Result<Q::Output, Box<dyn std::error::Error + Send + Sync>>;

    /// Dispatch the query with payload deserialization and output serialization.
    fn dispatch(
        &self,
        ctx: &WorkflowContextView,
        payloads: &Payloads,
        converter: &PayloadConverter,
    ) -> Result<Payload, WorkflowError> {
        let input = deserialize_input::<Q::Input>(payloads.payloads.clone(), converter)?;
        let output = self.handle(ctx, input).map_err(wrap_handler_error)?;
        serialize_output(&output, converter)
    }
}

/// Trait for executing synchronous update handlers on a workflow.
pub trait ExecutableSyncUpdate<U: UpdateDefinition>: WorkflowImplementation {
    /// Handle an update with the given input and return the result.
    fn handle(
        &mut self,
        ctx: &mut SyncWorkflowContext<Self>,
        input: U::Input,
    ) -> Result<U::Output, Box<dyn std::error::Error + Send + Sync>>;

    /// Validate an update before it is applied.
    fn validate(
        &self,
        _ctx: &WorkflowContextView,
        _input: &U::Input,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        Ok(())
    }

    /// Dispatch the update with payload deserialization and output serialization.
    fn dispatch(
        ctx: WorkflowContext<Self>,
        payloads: Payloads,
        converter: &PayloadConverter,
    ) -> LocalBoxFuture<'static, Result<Payload, WorkflowError>> {
        let input = match deserialize_input::<U::Input>(payloads.payloads, converter) {
            Ok(v) => v,
            Err(e) => return std::future::ready(Err(e)).boxed_local(),
        };
        let converter = converter.clone();
        let mut sync_ctx = ctx.sync_context();
        let result = ctx.state_mut(|wf| Self::handle(wf, &mut sync_ctx, input));
        match result {
            Ok(output) => match serialize_output(&output, &converter) {
                Ok(payload) => std::future::ready(Ok(payload)).boxed_local(),
                Err(e) => std::future::ready(Err(e)).boxed_local(),
            },
            Err(e) => std::future::ready(Err(wrap_handler_error(e))).boxed_local(),
        }
    }

    /// Dispatch validation with payload deserialization.
    fn dispatch_validate(
        &self,
        ctx: &WorkflowContextView,
        payloads: &Payloads,
        converter: &PayloadConverter,
    ) -> Result<(), WorkflowError> {
        let input = deserialize_input::<U::Input>(payloads.payloads.clone(), converter)?;
        self.validate(ctx, &input).map_err(wrap_handler_error)
    }
}

/// Trait for executing asynchronous update handlers on a workflow.
pub trait ExecutableAsyncUpdate<U: UpdateDefinition>: WorkflowImplementation {
    /// Handle an update with the given input and return the result.
    fn handle(
        ctx: WorkflowContext<Self>,
        input: U::Input,
    ) -> LocalBoxFuture<'static, Result<U::Output, Box<dyn std::error::Error + Send + Sync>>>;

    /// Validate an update before it is applied.
    fn validate(
        &self,
        _ctx: &WorkflowContextView,
        _input: &U::Input,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        Ok(())
    }

    /// Dispatch the update with payload deserialization and output serialization.
    fn dispatch(
        ctx: WorkflowContext<Self>,
        payloads: Payloads,
        converter: &PayloadConverter,
    ) -> LocalBoxFuture<'static, Result<Payload, WorkflowError>> {
        let input = match deserialize_input::<U::Input>(payloads.payloads, converter) {
            Ok(v) => v,
            Err(e) => return std::future::ready(Err(e)).boxed_local(),
        };
        let converter = converter.clone();
        async move {
            let output = Self::handle(ctx, input).await.map_err(wrap_handler_error)?;
            serialize_output(&output, &converter)
        }
        .boxed_local()
    }

    /// Dispatch validation with payload deserialization.
    fn dispatch_validate(
        &self,
        ctx: &WorkflowContextView,
        payloads: &Payloads,
        converter: &PayloadConverter,
    ) -> Result<(), WorkflowError> {
        let input = deserialize_input::<U::Input>(payloads.payloads.clone(), converter)?;
        self.validate(ctx, &input).map_err(wrap_handler_error)
    }
}

/// Deserialize handler input from payloads.
pub(crate) fn deserialize_input<I: TemporalDeserializable + 'static>(
    payloads: Vec<Payload>,
    converter: &PayloadConverter,
) -> Result<I, WorkflowError> {
    let ctx = SerializationContext {
        data: &SerializationContextData::Workflow,
        converter,
    };
    converter.from_payloads(&ctx, payloads).map_err(Into::into)
}

/// Serialize handler output to a payload.
pub(crate) fn serialize_output<O: TemporalSerializable + 'static>(
    output: &O,
    converter: &PayloadConverter,
) -> Result<Payload, WorkflowError> {
    let ctx = SerializationContext {
        data: &SerializationContextData::Workflow,
        converter,
    };
    converter.to_payload(&ctx, output).map_err(Into::into)
}

/// Wrap a handler error into WorkflowError.
pub(crate) fn wrap_handler_error(e: Box<dyn std::error::Error + Send + Sync>) -> WorkflowError {
    WorkflowError::Execution(anyhow::anyhow!(e))
}

/// Serialize a workflow result value to a payload.
pub fn serialize_result<T: TemporalSerializable + 'static>(
    result: T,
    converter: &PayloadConverter,
) -> Result<Payload, WorkflowError> {
    serialize_output(&result, converter)
}
