//! Contains types for activity definitions, used by the code generated by the macros for defining
//! activities, or directly by users targeting activities in other languages.

use crate::data_converters::{TemporalDeserializable, TemporalSerializable};

/// Typically, you will want to use the `#[activities]` and `#[activity]` macro to define activities.
/// However, this trait may be implemented manually if desired.
///
/// Implement on a marker struct to define an activity.
pub trait ActivityDefinition {
    /// Type of the input argument to the workflow
    type Input: TemporalDeserializable + 'static;
    /// Type of the output of the workflow
    type Output: TemporalSerializable + 'static;

    /// The name that will be used for the activity type.
    fn name() -> &'static str
    where
        Self: Sized;

    // TODO: Maybe can move this to a trait in SDK like "ExecutableActivityDefinition"
    // type Implementer: ActivityImplementer + 'static;
    // fn execute(
    //     receiver: Option<Arc<Self::Implementer>>,
    //     ctx: ActivityContext,
    //     input: Self::Input,
    // ) -> BoxFuture<'static, Result<Self::Output, ActivityError>>;
}

// TODO: Can likely also go in SDK
// pub trait ActivityImplementer {
//     fn register_all_static<S: worker_options_builder::State>(
//         worker_options: &mut WorkerOptionsBuilder<S>,
//     );
//     fn register_all_instance<S: worker_options_builder::State>(
//         self: Arc<Self>,
//         worker_options: &mut WorkerOptionsBuilder<S>,
//     );
// }
