name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-pull:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make docker-pull

  gen-cpp:
    needs: docker-pull
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make gen-cpp

  gen-csharp:
    needs: docker-pull
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make gen-csharp

  gen-go:
    needs: docker-pull
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make gen-go

  gen-java:
    needs: docker-pull
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make gen-java

  gen-objc:
    needs: docker-pull
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make gen-objc

  gen-openapi:
    needs: docker-pull
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make gen-openapi

  gen-php:
    needs: docker-pull
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make gen-php

  gen-python:
    needs: docker-pull
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make gen-python

  gen-ruby:
    needs: docker-pull
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make gen-ruby
